import { ArrayFieldTemplateProps } from '@rjsf/utils';
import { Plus } from 'lucide-react';
import { cn } from '@/lib/utils';

export const ArrayFieldTemplate = (props: ArrayFieldTemplateProps) => {
  const {
    canAdd,
    className,
    disabled,
    items,
    onAddClick,
    readonly,
    title,
    required,
    schema,
  } = props;
  
  const description = schema.description;

  // We render 'items' directly because they are React Elements generated by RJSF.
  // They will internally use our ArrayFieldItemTemplate.
  return (
    <div className={cn("w-full", className)}>
      {(title || description) && (
        <div className="mb-2 border-b pb-1">
          {title && (
            <div className="text-sm font-semibold text-foreground flex items-center gap-1">
              {title}
              {required && <span className="text-destructive">*</span>}
            </div>
          )}
          {description && (
            <div className="text-xs text-muted-foreground mt-0.5 opacity-90">
              {description}
            </div>
          )}
        </div>
      )}

      <div className="flex flex-col gap-1.5">
        {items}
      </div>

      {canAdd && (
        <div className="mt-2">
          <button
            type="button"
            className="flex items-center gap-1.5 text-[0.65rem] font-medium text-primary hover:text-primary/80 transition-colors px-2 py-1 rounded-md border border-dashed border-primary/30 hover:bg-primary/5"
            onClick={onAddClick}
            disabled={disabled || readonly}
          >
            <Plus className="w-3 h-3" />
            <span>Add Item</span>
          </button>
        </div>
      )}
    </div>
  );
};