/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_findAll"];
        put?: never;
        post: operations["WorkflowsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_findOne"];
        put: operations["WorkflowsController_update"];
        post?: never;
        delete: operations["WorkflowsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowsController_commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowsController_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{runId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{runId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowsController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{runId}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{runId}/dataflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_dataflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{runId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{runId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ComponentsController_listComponents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ComponentsController_getComponent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FilesController_uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FilesController_listFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FilesController_getFile"];
        put?: never;
        post?: never;
        delete: operations["FilesController_deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FilesController_downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SecretsController_listSecrets"];
        put?: never;
        post: operations["SecretsController_createSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secrets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SecretsController_getSecret"];
        put?: never;
        post?: never;
        delete: operations["SecretsController_deleteSecret"];
        options?: never;
        head?: never;
        patch: operations["SecretsController_updateSecret"];
        trace?: never;
    };
    "/secrets/{id}/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SecretsController_getSecretValue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secrets/{id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SecretsController_rotateSecret"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/testing/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestingWebhookController_listRecords"];
        put?: never;
        post: operations["TestingWebhookController_acceptWebhook"];
        delete: operations["TestingWebhookController_clearRecords"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/testing/webhooks/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestingWebhookController_latestRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/testing/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestingWebhookController_getRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateWorkflowRequestDto: {
            id?: string;
            name: string;
            description?: string;
            nodes: {
                id: string;
                type: string;
                position: {
                    x: number;
                    y: number;
                };
                data: {
                    label: string;
                    /** @default {} */
                    config: {
                        [key: string]: unknown;
                    };
                };
            }[];
            edges: {
                id: string;
                source: string;
                target: string;
                sourceHandle?: string;
                targetHandle?: string;
            }[];
            viewport: {
                x: number;
                y: number;
                zoom: number;
            };
        };
        WorkflowResponseDto: {
            id: string;
            name: string;
            description?: string | null;
            graph: {
                id?: string;
                name: string;
                description?: string;
                nodes: {
                    id: string;
                    type: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    data: {
                        label: string;
                        /** @default {} */
                        config: {
                            [key: string]: unknown;
                        };
                    };
                }[];
                edges: {
                    id: string;
                    source: string;
                    target: string;
                    sourceHandle?: string;
                    targetHandle?: string;
                }[];
                viewport: {
                    x: number;
                    y: number;
                    zoom: number;
                };
            };
            nodes: {
                id: string;
                type: string;
                position: {
                    x: number;
                    y: number;
                };
                data: {
                    label: string;
                    /** @default {} */
                    config: {
                        [key: string]: unknown;
                    };
                };
            }[];
            edges: {
                id: string;
                source: string;
                target: string;
                sourceHandle?: string;
                targetHandle?: string;
            }[];
            viewport: {
                x: number;
                y: number;
                zoom: number;
            };
            compiledDefinition: unknown;
            lastRun: string | null;
            runCount: number;
            createdAt: string;
            updatedAt: string;
        };
        UpdateWorkflowRequestDto: {
            id?: string;
            name: string;
            description?: string;
            nodes: {
                id: string;
                type: string;
                position: {
                    x: number;
                    y: number;
                };
                data: {
                    label: string;
                    /** @default {} */
                    config: {
                        [key: string]: unknown;
                    };
                };
            }[];
            edges: {
                id: string;
                source: string;
                target: string;
                sourceHandle?: string;
                targetHandle?: string;
            }[];
            viewport: {
                x: number;
                y: number;
                zoom: number;
            };
        };
        RunWorkflowRequestDto: {
            inputs?: {
                [key: string]: unknown;
            };
        };
        SecretVersionResponse: {
            id: string;
            version: number;
            /** Format: date-time */
            createdAt: string;
            createdBy?: string;
        };
        SecretSummaryResponse: {
            id: string;
            name: string;
            description?: string;
            tags?: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Metadata about the active version (value is never returned) */
            activeVersion?: components["schemas"]["SecretVersionResponse"];
        };
        SecretValueResponse: {
            secretId: string;
            version: number;
            /** @description Decrypted secret value */
            value: string;
        };
        CreateSecretDto: {
            /** @description Human-readable unique secret name */
            name: string;
            /** @description Secret plaintext value */
            value: string;
            /** @description Optional description for operators */
            description?: string;
            /** @description Optional tags to help organize secrets */
            tags?: string[];
        };
        RotateSecretDto: {
            /** @description New plaintext secret value */
            value: string;
        };
        UpdateSecretDto: {
            /** @description Updated secret name (must remain unique) */
            name?: string;
            /** @description Updated description for the secret */
            description?: string;
            /** @description Updated tags for the secret */
            tags?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponseDto"][];
                };
            };
        };
    };
    WorkflowsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponseDto"];
                };
            };
        };
    };
    WorkflowsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponseDto"];
                };
            };
        };
    };
    WorkflowsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkflowRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponseDto"];
                };
            };
        };
    };
    WorkflowsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_listRuns: {
        parameters: {
            query?: {
                workflowId?: string;
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all workflow runs with metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs?: {
                            id?: string;
                            workflowId?: string;
                            /** @enum {string} */
                            status?: "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "TERMINATED" | "CONTINUED_AS_NEW" | "TIMED_OUT" | "UNKNOWN";
                            /** Format: date-time */
                            startTime?: string;
                            /** Format: date-time */
                            endTime?: string | null;
                            temporalRunId?: string;
                            workflowName?: string;
                            eventCount?: number;
                        }[];
                    };
                };
            };
        };
    };
    WorkflowsController_commit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compiled workflow definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title?: string;
                        description?: string | null;
                        entrypoint?: {
                            ref?: string;
                        };
                        actions?: {
                            ref?: string;
                            componentId?: string;
                            params?: {
                                [key: string]: unknown;
                            };
                            dependsOn?: string[];
                        }[];
                        config?: {
                            environment?: string;
                            timeoutSeconds?: number;
                        };
                    };
                };
            };
        };
    };
    WorkflowsController_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunWorkflowRequestDto"];
            };
        };
        responses: {
            /** @description Workflow execution result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Temporal workflow identifier */
                        runId?: string;
                        /** @description Workflow record id */
                        workflowId?: string;
                        /** @description Temporal first execution run id */
                        temporalRunId?: string;
                        /** @description Temporal task queue used for execution */
                        taskQueue?: string;
                        /** @enum {string} */
                        status?: "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "TERMINATED" | "CONTINUED_AS_NEW" | "TIMED_OUT" | "UNKNOWN";
                    };
                };
            };
        };
    };
    WorkflowsController_status: {
        parameters: {
            query?: {
                temporalRunId?: string;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Temporal execution status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_result: {
        parameters: {
            query?: {
                temporalRunId?: string;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved workflow result payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_cancel: {
        parameters: {
            query?: {
                temporalRunId?: string;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancels a running workflow execution */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_trace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace events for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runId?: string;
                        events?: {
                            id?: string;
                            runId?: string;
                            nodeId?: string;
                            /** @enum {string} */
                            type?: "STARTED" | "PROGRESS" | "COMPLETED" | "FAILED";
                            /** @enum {string} */
                            level?: "info" | "warn" | "error" | "debug";
                            /** Format: date-time */
                            timestamp?: string;
                            message?: string | null;
                            error?: {
                                message?: string;
                                stack?: string;
                                code?: string;
                            } | null;
                            outputSummary?: {
                                [key: string]: unknown;
                            } | null;
                            data?: {
                                [key: string]: unknown;
                            } | null;
                            metadata?: {
                                activityId?: string;
                                attempt?: number;
                                correlationId?: string;
                                streamId?: string;
                                /** @enum {string} */
                                joinStrategy?: "all" | "any" | "first";
                                triggeredBy?: string;
                                failure?: {
                                    /** Format: date-time */
                                    at?: string;
                                    reason?: {
                                        message?: string;
                                        name?: string;
                                    };
                                } | null;
                                retryPolicy?: {
                                    maxAttempts?: number;
                                    initialIntervalSeconds?: number;
                                    maximumIntervalSeconds?: number;
                                    backoffCoefficient?: number;
                                    nonRetryableErrorTypes?: string[];
                                } | null;
                            } | null;
                        }[];
                        cursor?: string | null;
                    };
                };
            };
        };
    };
    WorkflowsController_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full event timeline for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runId?: string;
                        events?: {
                            id?: string;
                            runId?: string;
                            nodeId?: string;
                            /** @enum {string} */
                            type?: "STARTED" | "PROGRESS" | "COMPLETED" | "FAILED";
                            /** @enum {string} */
                            level?: "info" | "warn" | "error" | "debug";
                            /** Format: date-time */
                            timestamp?: string;
                            message?: string | null;
                            error?: {
                                message?: string;
                                stack?: string;
                                code?: string;
                            } | null;
                            outputSummary?: {
                                [key: string]: unknown;
                            } | null;
                            data?: {
                                [key: string]: unknown;
                            } | null;
                            metadata?: {
                                activityId?: string;
                                attempt?: number;
                                correlationId?: string;
                                streamId?: string;
                                /** @enum {string} */
                                joinStrategy?: "all" | "any" | "first";
                                triggeredBy?: string;
                                failure?: {
                                    /** Format: date-time */
                                    at?: string;
                                    reason?: {
                                        message?: string;
                                        name?: string;
                                    };
                                } | null;
                                retryPolicy?: {
                                    maxAttempts?: number;
                                    initialIntervalSeconds?: number;
                                    maximumIntervalSeconds?: number;
                                    backoffCoefficient?: number;
                                    nonRetryableErrorTypes?: string[];
                                } | null;
                            } | null;
                        }[];
                        cursor?: string | null;
                    };
                };
            };
        };
    };
    WorkflowsController_dataflows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Derived data flow packets for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runId?: string;
                        packets?: {
                            id?: string;
                            runId?: string;
                            sourceNode?: string;
                            targetNode?: string;
                            inputKey?: string | null;
                            payload?: {
                                [key: string]: unknown;
                            } | null;
                            timestamp?: number;
                            visualTime?: number;
                            size?: number;
                            /** @enum {string} */
                            type?: "file" | "json" | "text" | "binary";
                        }[];
                    };
                };
            };
        };
    };
    WorkflowsController_stream: {
        parameters: {
            query?: {
                temporalRunId?: string;
                cursor?: string;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events stream for workflow run updates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_logs: {
        parameters: {
            query?: {
                nodeRef?: string;
                stream?: string;
                limit?: number;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log streams for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ComponentsController_listComponents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all registered components */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example core.file.loader */
                        id?: string;
                        /** @example file-loader */
                        slug?: string;
                        /** @example File Loader */
                        name?: string;
                        /** @example 1.0.0 */
                        version?: string;
                        /** @example input */
                        type?: string;
                        /** @example input-output */
                        category?: string;
                        /** @example Load files from filesystem */
                        description?: string;
                        documentation?: string | null;
                        documentationUrl?: string | null;
                        /** @example FileUp */
                        icon?: string;
                        logo?: string | null;
                        isLatest?: boolean | null;
                        deprecated?: boolean | null;
                        example?: string | null;
                        author?: {
                            name?: string;
                            /** @enum {string} */
                            type?: "shipsecai" | "community";
                            url?: string | null;
                        } | null;
                        runner?: {
                            /**
                             * @example inline
                             * @enum {string}
                             */
                            kind?: "inline" | "docker" | "remote";
                            image?: string | null;
                            command?: string[] | null;
                        };
                        inputs?: {
                            id?: string;
                            label?: string;
                            type?: ("string" | "array" | "object" | "file" | "secret" | "number") | ("string" | "array" | "object" | "file" | "secret" | "number")[];
                            required?: boolean;
                            description?: string | null;
                        }[];
                        outputs?: {
                            id?: string;
                            label?: string;
                            /** @enum {string} */
                            type?: "string" | "array" | "object" | "file" | "secret" | "number";
                            description?: string | null;
                        }[];
                        parameters?: {
                            id?: string;
                            label?: string;
                            /** @enum {string} */
                            type?: "text" | "textarea" | "number" | "boolean" | "select" | "multi-select" | "json" | "secret";
                            required?: boolean;
                            default?: unknown;
                            placeholder?: string | null;
                            description?: string | null;
                            helpText?: string | null;
                            options?: {
                                label?: string;
                                value?: unknown;
                            }[] | null;
                            min?: number | null;
                            max?: number | null;
                            rows?: number | null;
                        }[];
                        examples?: string[];
                    }[];
                };
            };
        };
    };
    ComponentsController_getComponent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get a specific component by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description File to upload
                     */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description File uploaded successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        fileName?: string;
                        mimeType?: string;
                        size?: number;
                        storageKey?: string;
                        /** Format: date-time */
                        uploadedAt?: string;
                    };
                };
            };
        };
    };
    FilesController_listFiles: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all uploaded files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        fileName?: string;
                        mimeType?: string;
                        size?: number;
                        /** Format: date-time */
                        uploadedAt?: string;
                    }[];
                };
            };
        };
    };
    FilesController_getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get file metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    SecretsController_listSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSummaryResponse"][];
                };
            };
        };
    };
    SecretsController_createSecret: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSecretDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSummaryResponse"];
                };
            };
        };
    };
    SecretsController_getSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSummaryResponse"];
                };
            };
        };
    };
    SecretsController_deleteSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SecretsController_updateSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSecretDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSummaryResponse"];
                };
            };
        };
    };
    SecretsController_getSecretValue: {
        parameters: {
            query?: {
                /** @description Optional secret version to retrieve (defaults to active version) */
                version?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretValueResponse"];
                };
            };
        };
    };
    SecretsController_rotateSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateSecretDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSummaryResponse"];
                };
            };
        };
    };
    TestingWebhookController_listRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestingWebhookController_acceptWebhook: {
        parameters: {
            query?: {
                status?: number;
                delayMs?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestingWebhookController_clearRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestingWebhookController_latestRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestingWebhookController_getRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
