/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_findAll"];
        put?: never;
        post: operations["WorkflowsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_findOne"];
        put: operations["WorkflowsController_update"];
        post?: never;
        delete: operations["WorkflowsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_findVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowsController_commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowsController_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowsController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/dataflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_dataflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_runArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/artifacts/{artifactId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_downloadRunArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/runs/{runId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FilesController_uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FilesController_listFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FilesController_getFile"];
        put?: never;
        post?: never;
        delete: operations["FilesController_deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FilesController_downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArtifactsController_listArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArtifactsController_downloadArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ComponentsController_listComponents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/components/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ComponentsController_getComponent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SecretsController_listSecrets"];
        put?: never;
        post: operations["SecretsController_createSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/secrets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SecretsController_getSecret"];
        put?: never;
        post?: never;
        delete: operations["SecretsController_deleteSecret"];
        options?: never;
        head?: never;
        patch: operations["SecretsController_updateSecret"];
        trace?: never;
    };
    "/api/v1/secrets/{id}/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SecretsController_getSecretValue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/secrets/{id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SecretsController_rotateSecret"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IntegrationsController_listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/providers/{provider}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IntegrationsController_getProviderConfiguration"];
        put: operations["IntegrationsController_upsertProviderConfiguration"];
        post?: never;
        delete: operations["IntegrationsController_deleteProviderConfiguration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IntegrationsController_listConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IntegrationsController_startOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/{provider}/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IntegrationsController_completeOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/connections/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IntegrationsController_refreshConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["IntegrationsController_disconnectConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/connections/{id}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IntegrationsController_issueConnectionToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/testing/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestingWebhookController_listRecords"];
        put?: never;
        post: operations["TestingWebhookController_acceptWebhook"];
        delete: operations["TestingWebhookController_clearRecords"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/testing/webhooks/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestingWebhookController_latestRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/testing/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestingWebhookController_getRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateWorkflowRequestDto: {
            id?: string;
            name: string;
            description?: string;
            nodes: {
                id: string;
                type: string;
                position: {
                    x: number;
                    y: number;
                };
                data: {
                    label: string;
                    /** @default {} */
                    config: {
                        [key: string]: unknown;
                    };
                };
            }[];
            edges: {
                id: string;
                source: string;
                target: string;
                sourceHandle?: string;
                targetHandle?: string;
            }[];
            viewport: {
                x: number;
                y: number;
                zoom: number;
            };
        };
        WorkflowResponseDto: {
            id: string;
            name: string;
            description?: string | null;
            graph: {
                id?: string;
                name: string;
                description?: string;
                nodes: {
                    id: string;
                    type: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    data: {
                        label: string;
                        /** @default {} */
                        config: {
                            [key: string]: unknown;
                        };
                    };
                }[];
                edges: {
                    id: string;
                    source: string;
                    target: string;
                    sourceHandle?: string;
                    targetHandle?: string;
                }[];
                viewport: {
                    x: number;
                    y: number;
                    zoom: number;
                };
            };
            compiledDefinition: unknown;
            lastRun: string | null;
            runCount: number;
            createdAt: string;
            updatedAt: string;
            /** Format: uuid */
            currentVersionId: string | null;
            currentVersion: number | null;
        };
        UpdateWorkflowRequestDto: {
            id?: string;
            name: string;
            description?: string;
            nodes: {
                id: string;
                type: string;
                position: {
                    x: number;
                    y: number;
                };
                data: {
                    label: string;
                    /** @default {} */
                    config: {
                        [key: string]: unknown;
                    };
                };
            }[];
            edges: {
                id: string;
                source: string;
                target: string;
                sourceHandle?: string;
                targetHandle?: string;
            }[];
            viewport: {
                x: number;
                y: number;
                zoom: number;
            };
        };
        WorkflowVersionResponseDto: {
            id: string;
            workflowId: string;
            version: number;
            graph: {
                id?: string;
                name: string;
                description?: string;
                nodes: {
                    id: string;
                    type: string;
                    position: {
                        x: number;
                        y: number;
                    };
                    data: {
                        label: string;
                        /** @default {} */
                        config: {
                            [key: string]: unknown;
                        };
                    };
                }[];
                edges: {
                    id: string;
                    source: string;
                    target: string;
                    sourceHandle?: string;
                    targetHandle?: string;
                }[];
                viewport: {
                    x: number;
                    y: number;
                    zoom: number;
                };
            };
            createdAt: string;
            updatedAt: string;
        };
        RunWorkflowRequestDto: {
            inputs?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            versionId?: string;
            version?: number;
        };
        RunArtifactsResponseDto: {
            runId: string;
            artifacts: {
                /** Format: uuid */
                id: string;
                runId: string;
                /** Format: uuid */
                workflowId: string;
                /** Format: uuid */
                workflowVersionId?: string | null;
                componentId?: string | null;
                componentRef: string;
                /** Format: uuid */
                fileId: string;
                name: string;
                mimeType: string;
                size: number;
                destinations: ("run" | "library")[];
                metadata?: ({
                    remoteUploads?: {
                        /** @enum {string} */
                        type: "s3" | "gcs";
                        bucket: string;
                        key: string;
                        uri: string;
                        region?: string;
                        size?: number;
                        etag?: string;
                        /** Format: uri */
                        url?: string;
                        metadata?: {
                            [key: string]: unknown;
                        };
                    }[];
                } & {
                    [key: string]: unknown;
                }) | null;
                organizationId?: string | null;
                /** Format: date-time */
                createdAt: string;
            }[];
        };
        ArtifactListResponseDto: {
            artifacts: {
                /** Format: uuid */
                id: string;
                runId: string;
                /** Format: uuid */
                workflowId: string;
                /** Format: uuid */
                workflowVersionId?: string | null;
                componentId?: string | null;
                componentRef: string;
                /** Format: uuid */
                fileId: string;
                name: string;
                mimeType: string;
                size: number;
                destinations: ("run" | "library")[];
                metadata?: ({
                    remoteUploads?: {
                        /** @enum {string} */
                        type: "s3" | "gcs";
                        bucket: string;
                        key: string;
                        uri: string;
                        region?: string;
                        size?: number;
                        etag?: string;
                        /** Format: uri */
                        url?: string;
                        metadata?: {
                            [key: string]: unknown;
                        };
                    }[];
                } & {
                    [key: string]: unknown;
                }) | null;
                organizationId?: string | null;
                /** Format: date-time */
                createdAt: string;
            }[];
        };
        SecretVersionResponse: {
            id: string;
            version: number;
            /** Format: date-time */
            createdAt: string;
            createdBy?: string;
        };
        SecretSummaryResponse: {
            id: string;
            name: string;
            description?: string;
            tags?: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Metadata about the active version (value is never returned) */
            activeVersion?: components["schemas"]["SecretVersionResponse"];
        };
        SecretValueResponse: {
            secretId: string;
            version: number;
            /** @description Decrypted secret value */
            value: string;
        };
        CreateSecretDto: {
            /** @description Human-readable unique secret name */
            name: string;
            /** @description Secret plaintext value */
            value: string;
            /** @description Optional description for operators */
            description?: string;
            /** @description Optional tags to help organize secrets */
            tags?: string[];
        };
        RotateSecretDto: {
            /** @description New plaintext secret value */
            value: string;
        };
        UpdateSecretDto: {
            /** @description Updated secret name (must remain unique) */
            name?: string;
            /** @description Updated description for the secret */
            description?: string;
            /** @description Updated tags for the secret */
            tags?: string[];
        };
        IntegrationProviderResponse: {
            id: string;
            name: string;
            description: string;
            docsUrl?: string;
            defaultScopes: string[];
            supportsRefresh: boolean;
            /** @description Indicates whether the provider has been configured with client credentials */
            isConfigured: boolean;
        };
        ProviderConfigurationResponse: {
            provider: string;
            /** @description Stored OAuth client identifier */
            clientId?: string;
            /** @description True when a client secret has been stored for this provider */
            hasClientSecret: boolean;
            /**
             * @description Origin of the credential configuration
             * @enum {string}
             */
            configuredBy: "environment" | "user";
            /** @description Last update timestamp in ISO 8601 format */
            updatedAt?: string;
        };
        UpsertProviderConfigDto: {
            /** @description OAuth client identifier used for this provider */
            clientId: string;
            /** @description OAuth client secret. Required when configuring the provider for the first time. */
            clientSecret?: string;
        };
        IntegrationConnectionResponse: {
            id: string;
            provider: string;
            providerName: string;
            userId: string;
            scopes: string[];
            tokenType: string;
            expiresAt?: string;
            createdAt: string;
            updatedAt: string;
            /** @enum {string} */
            status: "active" | "expired";
            supportsRefresh: boolean;
            hasRefreshToken: boolean;
            /** @description Provider-specific metadata saved alongside the connection */
            metadata?: Record<string, never>;
        };
        StartOAuthDto: {
            /** @description Application user identifier to associate the connection with */
            userId: string;
            /** @description Frontend callback URL that receives the OAuth code */
            redirectUri: string;
            /** @description Optional override of scopes to request */
            scopes?: string[];
        };
        OAuthStartResponseDto: {
            provider: string;
            authorizationUrl: string;
            state: string;
            /**
             * @description Suggested client-side TTL for the authorization URL
             * @example 300
             */
            expiresIn: number;
        };
        CompleteOAuthDto: {
            /** @description Application user identifier to associate the connection with */
            userId: string;
            /** @description Frontend callback URL that receives the OAuth code */
            redirectUri: string;
            /** @description Optional override of scopes to request */
            scopes?: string[];
            /** @description Opaque OAuth state returned from the authorize redirect */
            state: string;
            /** @description Authorization code issued by the provider */
            code: string;
        };
        RefreshConnectionDto: {
            /** @description Application user identifier that owns the connection */
            userId: string;
        };
        DisconnectConnectionDto: {
            /** @description Application user identifier that owns the connection */
            userId: string;
        };
        ConnectionTokenResponseDto: {
            provider: string;
            userId: string;
            accessToken: string;
            tokenType: string;
            scopes: string[];
            expiresAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponseDto"][];
                };
            };
        };
    };
    WorkflowsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponseDto"];
                };
            };
        };
    };
    WorkflowsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponseDto"];
                };
            };
        };
    };
    WorkflowsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkflowRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponseDto"];
                };
            };
        };
    };
    WorkflowsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_listRuns: {
        parameters: {
            query?: {
                workflowId?: string;
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all workflow runs with metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs?: {
                            id?: string;
                            workflowId?: string;
                            /** @enum {string} */
                            status?: "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "TERMINATED" | "CONTINUED_AS_NEW" | "TIMED_OUT" | "UNKNOWN";
                            /** Format: date-time */
                            startTime?: string;
                            /** Format: date-time */
                            endTime?: string | null;
                            temporalRunId?: string;
                            workflowVersionId?: string | null;
                            workflowVersion?: number | null;
                            workflowName?: string;
                            eventCount?: number;
                            nodeCount?: number;
                            duration?: number;
                        }[];
                    };
                };
            };
        };
    };
    WorkflowsController_findVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowVersionResponseDto"];
                };
            };
        };
    };
    WorkflowsController_commit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compiled workflow definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title?: string;
                        description?: string | null;
                        entrypoint?: {
                            ref?: string;
                        };
                        actions?: {
                            ref?: string;
                            componentId?: string;
                            params?: {
                                [key: string]: unknown;
                            };
                            dependsOn?: string[];
                        }[];
                        config?: {
                            environment?: string;
                            timeoutSeconds?: number;
                        };
                    };
                };
            };
        };
    };
    WorkflowsController_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunWorkflowRequestDto"];
            };
        };
        responses: {
            /** @description Workflow execution result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Temporal workflow identifier */
                        runId?: string;
                        /** @description Workflow record id */
                        workflowId?: string;
                        /** @description Temporal first execution run id */
                        temporalRunId?: string;
                        /** @description Temporal task queue used for execution */
                        taskQueue?: string;
                        /** @description Workflow version identifier used for execution */
                        workflowVersionId?: string;
                        /** @description Workflow version number used for execution */
                        workflowVersion?: number;
                        /** @enum {string} */
                        status?: "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "TERMINATED" | "CONTINUED_AS_NEW" | "TIMED_OUT" | "UNKNOWN";
                    };
                };
            };
        };
    };
    WorkflowsController_status: {
        parameters: {
            query?: {
                temporalRunId?: string;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Temporal execution status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_result: {
        parameters: {
            query?: {
                temporalRunId?: string;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved workflow result payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inputs and version metadata captured for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runId?: string;
                        workflowId?: string;
                        workflowVersionId?: string | null;
                        workflowVersion?: number | null;
                        inputs?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    WorkflowsController_cancel: {
        parameters: {
            query?: {
                temporalRunId?: string;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancels a running workflow execution */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_trace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace events for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runId?: string;
                        events?: {
                            id?: string;
                            runId?: string;
                            nodeId?: string;
                            /** @enum {string} */
                            type?: "STARTED" | "PROGRESS" | "COMPLETED" | "FAILED";
                            /** @enum {string} */
                            level?: "info" | "warn" | "error" | "debug";
                            /** Format: date-time */
                            timestamp?: string;
                            message?: string | null;
                            error?: {
                                message?: string;
                                stack?: string;
                                code?: string;
                            } | null;
                            outputSummary?: {
                                [key: string]: unknown;
                            } | null;
                            data?: {
                                [key: string]: unknown;
                            } | null;
                            metadata?: {
                                activityId?: string;
                                attempt?: number;
                                correlationId?: string;
                                streamId?: string;
                                /** @enum {string} */
                                joinStrategy?: "all" | "any" | "first";
                                triggeredBy?: string;
                                failure?: {
                                    /** Format: date-time */
                                    at?: string;
                                    reason?: {
                                        message?: string;
                                        name?: string;
                                    };
                                } | null;
                                retryPolicy?: {
                                    maxAttempts?: number;
                                    initialIntervalSeconds?: number;
                                    maximumIntervalSeconds?: number;
                                    backoffCoefficient?: number;
                                    nonRetryableErrorTypes?: string[];
                                } | null;
                            } | null;
                        }[];
                        cursor?: string | null;
                    };
                };
            };
        };
    };
    WorkflowsController_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full event timeline for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runId?: string;
                        events?: {
                            id?: string;
                            runId?: string;
                            nodeId?: string;
                            /** @enum {string} */
                            type?: "STARTED" | "PROGRESS" | "COMPLETED" | "FAILED";
                            /** @enum {string} */
                            level?: "info" | "warn" | "error" | "debug";
                            /** Format: date-time */
                            timestamp?: string;
                            message?: string | null;
                            error?: {
                                message?: string;
                                stack?: string;
                                code?: string;
                            } | null;
                            outputSummary?: {
                                [key: string]: unknown;
                            } | null;
                            data?: {
                                [key: string]: unknown;
                            } | null;
                            metadata?: {
                                activityId?: string;
                                attempt?: number;
                                correlationId?: string;
                                streamId?: string;
                                /** @enum {string} */
                                joinStrategy?: "all" | "any" | "first";
                                triggeredBy?: string;
                                failure?: {
                                    /** Format: date-time */
                                    at?: string;
                                    reason?: {
                                        message?: string;
                                        name?: string;
                                    };
                                } | null;
                                retryPolicy?: {
                                    maxAttempts?: number;
                                    initialIntervalSeconds?: number;
                                    maximumIntervalSeconds?: number;
                                    backoffCoefficient?: number;
                                    nonRetryableErrorTypes?: string[];
                                } | null;
                            } | null;
                        }[];
                        cursor?: string | null;
                    };
                };
            };
        };
    };
    WorkflowsController_dataflows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Derived data flow packets for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runId?: string;
                        packets?: {
                            id?: string;
                            runId?: string;
                            sourceNode?: string;
                            targetNode?: string;
                            inputKey?: string | null;
                            payload?: {
                                [key: string]: unknown;
                            } | null;
                            timestamp?: number;
                            visualTime?: number;
                            size?: number;
                            /** @enum {string} */
                            type?: "file" | "json" | "text" | "binary";
                        }[];
                    };
                };
            };
        };
    };
    WorkflowsController_runArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifacts generated for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunArtifactsResponseDto"];
                };
            };
        };
    };
    WorkflowsController_downloadRunArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download artifact for a specific run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_stream: {
        parameters: {
            query?: {
                temporalRunId?: string;
                cursor?: string;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events stream for workflow run updates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_logs: {
        parameters: {
            query?: {
                nodeRef?: string;
                stream?: string;
                limit?: number;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log streams for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description File to upload
                     */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description File uploaded successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        fileName?: string;
                        mimeType?: string;
                        size?: number;
                        storageKey?: string;
                        /** Format: date-time */
                        uploadedAt?: string;
                    };
                };
            };
        };
    };
    FilesController_listFiles: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all uploaded files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        fileName?: string;
                        mimeType?: string;
                        size?: number;
                        /** Format: date-time */
                        uploadedAt?: string;
                    }[];
                };
            };
        };
    };
    FilesController_getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get file metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    ArtifactsController_listArtifacts: {
        parameters: {
            query?: {
                limit?: number;
                workflowId?: string;
                componentId?: string;
                destination?: "run" | "library";
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List workspace artifacts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListResponseDto"];
                };
            };
        };
    };
    ArtifactsController_downloadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download artifact binary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    ComponentsController_listComponents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all registered components */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example core.file.loader */
                        id?: string;
                        /** @example file-loader */
                        slug?: string;
                        /** @example File Loader */
                        name?: string;
                        /** @example 1.0.0 */
                        version?: string;
                        /** @example input */
                        type?: string;
                        /** @example input */
                        category?: string;
                        categoryConfig?: {
                            /** @example 📥 Input */
                            label?: string;
                            /** @example text-blue-600 */
                            color?: string;
                            /** @example Data sources, triggers, and credential access */
                            description?: string;
                            /** @example 📥 */
                            emoji?: string;
                        };
                        /** @example Load files from filesystem */
                        description?: string;
                        documentation?: string | null;
                        documentationUrl?: string | null;
                        /** @example FileUp */
                        icon?: string;
                        logo?: string | null;
                        isLatest?: boolean | null;
                        deprecated?: boolean | null;
                        example?: string | null;
                        author?: {
                            name?: string;
                            /** @enum {string} */
                            type?: "shipsecai" | "community";
                            url?: string | null;
                        } | null;
                        runner?: {
                            /**
                             * @example inline
                             * @enum {string}
                             */
                            kind?: "inline" | "docker" | "remote";
                            image?: string | null;
                            command?: string[] | null;
                        };
                        inputs?: {
                            id?: string;
                            label?: string;
                            dataType?: {
                                /** @enum {string} */
                                kind: "primitive" | "list" | "map" | "contract";
                                name?: string;
                                element?: Record<string, never>;
                                value?: Record<string, never>;
                                coercion?: {
                                    from?: ("any" | "text" | "secret" | "number" | "boolean" | "file" | "json")[];
                                };
                            } & {
                                [key: string]: unknown;
                            };
                            required?: boolean;
                            description?: string | null;
                            /** @enum {string|null} */
                            valuePriority?: "manual-first" | "connection-first" | null;
                        }[];
                        outputs?: {
                            id?: string;
                            label?: string;
                            dataType?: {
                                /** @enum {string} */
                                kind: "primitive" | "list" | "map" | "contract";
                                name?: string;
                                element?: Record<string, never>;
                                value?: Record<string, never>;
                                coercion?: {
                                    from?: ("any" | "text" | "secret" | "number" | "boolean" | "file" | "json")[];
                                };
                            } & {
                                [key: string]: unknown;
                            };
                            description?: string | null;
                        }[];
                        parameters?: {
                            id?: string;
                            label?: string;
                            /** @enum {string} */
                            type?: "text" | "textarea" | "number" | "boolean" | "select" | "multi-select" | "json" | "secret";
                            required?: boolean;
                            default?: unknown;
                            placeholder?: string | null;
                            description?: string | null;
                            helpText?: string | null;
                            options?: {
                                label?: string;
                                value?: unknown;
                            }[] | null;
                            min?: number | null;
                            max?: number | null;
                            rows?: number | null;
                        }[];
                        examples?: string[];
                    }[];
                };
            };
        };
    };
    ComponentsController_getComponent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get a specific component by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        slug?: string;
                        name?: string;
                        version?: string;
                        type?: string;
                        category?: string;
                        categoryConfig?: {
                            label?: string;
                            color?: string;
                            description?: string;
                            emoji?: string;
                        };
                        description?: string | null;
                        documentation?: string | null;
                        documentationUrl?: string | null;
                        icon?: string | null;
                        logo?: string | null;
                        author?: {
                            name?: string;
                            type?: string;
                            url?: string | null;
                        } | null;
                        runner?: Record<string, never>;
                        inputs?: {
                            id?: string;
                            label?: string;
                            dataType?: {
                                /** @enum {string} */
                                kind: "primitive" | "list" | "map" | "contract";
                                name?: string;
                                element?: Record<string, never>;
                                value?: Record<string, never>;
                                coercion?: {
                                    from?: ("any" | "text" | "secret" | "number" | "boolean" | "file" | "json")[];
                                };
                            } & {
                                [key: string]: unknown;
                            };
                            required?: boolean;
                            description?: string | null;
                            /** @enum {string|null} */
                            valuePriority?: "manual-first" | "connection-first" | null;
                        }[];
                        outputs?: {
                            id?: string;
                            label?: string;
                            dataType?: {
                                /** @enum {string} */
                                kind: "primitive" | "list" | "map" | "contract";
                                name?: string;
                                element?: Record<string, never>;
                                value?: Record<string, never>;
                                coercion?: {
                                    from?: ("any" | "text" | "secret" | "number" | "boolean" | "file" | "json")[];
                                };
                            } & {
                                [key: string]: unknown;
                            };
                            description?: string | null;
                        }[];
                        parameters?: unknown[];
                        examples?: unknown[];
                        isLatest?: boolean | null;
                        deprecated?: boolean | null;
                        example?: string | null;
                    };
                };
            };
        };
    };
    SecretsController_listSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSummaryResponse"][];
                };
            };
        };
    };
    SecretsController_createSecret: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSecretDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSummaryResponse"];
                };
            };
        };
    };
    SecretsController_getSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSummaryResponse"];
                };
            };
        };
    };
    SecretsController_deleteSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SecretsController_updateSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSecretDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSummaryResponse"];
                };
            };
        };
    };
    SecretsController_getSecretValue: {
        parameters: {
            query?: {
                /** @description Optional secret version to retrieve (defaults to active version) */
                version?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretValueResponse"];
                };
            };
        };
    };
    SecretsController_rotateSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateSecretDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSummaryResponse"];
                };
            };
        };
    };
    IntegrationsController_listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationProviderResponse"][];
                };
            };
        };
    };
    IntegrationsController_getProviderConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfigurationResponse"];
                };
            };
        };
    };
    IntegrationsController_upsertProviderConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProviderConfigDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfigurationResponse"];
                };
            };
        };
    };
    IntegrationsController_deleteProviderConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IntegrationsController_listConnections: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationConnectionResponse"][];
                };
            };
        };
    };
    IntegrationsController_startOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartOAuthDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStartResponseDto"];
                };
            };
        };
    };
    IntegrationsController_completeOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteOAuthDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationConnectionResponse"];
                };
            };
        };
    };
    IntegrationsController_refreshConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshConnectionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationConnectionResponse"];
                };
            };
        };
    };
    IntegrationsController_disconnectConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisconnectConnectionDto"];
            };
        };
        responses: {
            /** @description Connection removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IntegrationsController_issueConnectionToken: {
        parameters: {
            query?: never;
            header: {
                "x-internal-token": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTokenResponseDto"];
                };
            };
        };
    };
    TestingWebhookController_listRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestingWebhookController_acceptWebhook: {
        parameters: {
            query?: {
                status?: number;
                delayMs?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestingWebhookController_clearRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestingWebhookController_latestRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestingWebhookController_getRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
